# Application
spring.application.name=order-service
server.port=${SERVER_PORT:8083}

# Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/order_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Service URLs (for Feign clients)
services.catalog.url=http://localhost:8081
services.inventory.url=http://localhost:8082
services.payment.url=http://localhost:8084

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.pattern.console={"timestamp":"%d{ISO8601}","level":"%p","service":"order-service","traceId":"%X{traceId}","message":"%m"}%n
logging.level.com.example.order=DEBUG